// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsbH2ihYBO2a-h4snz7ElD7AdcSex2xXs',
    appId: '1:442579709675:web:6aba96e391129a4fb858ae',
    messagingSenderId: '442579709675',
    projectId: 'thrifttracker-3f14f',
    authDomain: 'thrifttracker-3f14f.firebaseapp.com',
    storageBucket: 'thrifttracker-3f14f.firebasestorage.app',
    measurementId: 'G-P06LTBSSQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnr5DmQbDkSTgESXOLwHXGKQoakfGO4pw',
    appId: '1:442579709675:android:7e12d2a84ade275eb858ae',
    messagingSenderId: '442579709675',
    projectId: 'thrifttracker-3f14f',
    storageBucket: 'thrifttracker-3f14f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlw-65nui-CT5mE9Mi6z0_jAPZkVVu_1Y',
    appId: '1:442579709675:ios:fdac69ad6329f8c0b858ae',
    messagingSenderId: '442579709675',
    projectId: 'thrifttracker-3f14f',
    storageBucket: 'thrifttracker-3f14f.firebasestorage.app',
    iosBundleId: 'com.example.thrifty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlw-65nui-CT5mE9Mi6z0_jAPZkVVu_1Y',
    appId: '1:442579709675:ios:fdac69ad6329f8c0b858ae',
    messagingSenderId: '442579709675',
    projectId: 'thrifttracker-3f14f',
    storageBucket: 'thrifttracker-3f14f.firebasestorage.app',
    iosBundleId: 'com.example.thrifty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsbH2ihYBO2a-h4snz7ElD7AdcSex2xXs',
    appId: '1:442579709675:web:fe72c304020e2c16b858ae',
    messagingSenderId: '442579709675',
    projectId: 'thrifttracker-3f14f',
    authDomain: 'thrifttracker-3f14f.firebaseapp.com',
    storageBucket: 'thrifttracker-3f14f.firebasestorage.app',
    measurementId: 'G-ZZYW1G6SDX',
  );
}
